### PR TITLE
[134] About Me

### PR DESCRIPTION
**Pull request by RafiatAmin**
"[134] About Me"

### CODE REVIEW

**Comment by RafiatAmin** [comment]
"[134] About Me"

**Comment by Ireti203** [comment]
Weldone @RafiatAmin The PR title is incorrect. Kindly check criteria 10 of this task and use the recommended title.

**Review by Ireti203 — CHANGES_REQUESTED** [review]
I can see that you have made changes to 9 other files asides your aboutme.txt file. Kindly make sure you are pushing only your aboutme.txt file.

**Review by RafiatAmin — COMMENTED** [review]
"[134] About Me"

**Comment by Ireti203** [comment]
Remove the quotation marks on your PR title, It should be [134] About me.

**Comment by RafiatAmin** [comment]
Hello,
I didn't make any changes to other files.

**Comment by Ireti203** [comment]
I can see that you have edited the title of the PR and now have the correct one, but it is best you close the PR and create a new one with the correct title instead.

**Comment by Ireti203** [comment]
I can see a .DS_Store file in project folders belonging to other scholars. You must have mistakenly made this change. Kindly revert.

You can click on files changed on this PR to view the affected folders.

**Pull request closed without merging**
