### PR TITLE
[136] About me

### PR DESCRIPTION
**Pull request by Aarinolaa**
I created an about me file and added what I hope to achieve at the end of the program.

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @Aarinolaa The PR title is not properly written. Kindly remove the quotation mark before the square bracket. You will have to close the PR and create a new one with the proper title.

**Comment by Aarinolaa** [comment]
Dear Ireti, thank you for the feedback. I will do as instructed. However, I
am not sure I know how to close the request. Kindly advise.
Regards,
Arinola

**Comment by Ireti203** [comment]
Screenshot 2020-12-26 113433
Scroll down the view of your PR, you will see the image above. You can close the PR by clicking on "Close Pull Request".

**Comment by Aarinolaa** [comment]
Got it, thanks! Will do same

**Comment by Aarinolaa** [comment]
Dear Ireti,

I couldn’t find that option so i edited the title after i did a commit on
my about me file. Kindly assess and advise.
Regards,
Arinola

**Pull request closed without merging**
