### PR TITLE
[153] Style the Product Details Page using CSS - Fullstack

### PR DESCRIPTION
**Pull request by misturaeneeolah**
I styled my product page with CSS and made it responsive to other devices including tablet and mobile.

css1
css2

### CODE REVIEW

**Comment by Ireti203** [comment]
weldone @misturaeneeolah Kindly attach the screenshots of the tablet and mobile view to this PR.

**Comment by misturaeneeolah** [comment]
Tablet and mobile implementations.

tablet1
tablet2
css1
mobile1
mobile2

**Review by adaugochi — CHANGES_REQUESTED** [review]
These two files are part of your PR 
image
The first one is empty and the second contains `css` code which is already on your `css` folder

**Comment by Ireti203** [comment]
The productpage.css file occurs in two places. You have one in your css folder and another in the folder with your name as the title. Kindly correct this repetition.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
