### PR TITLE
[136] About Me Task

### PR DESCRIPTION
**Pull request by Kafabidemi**
I added an aboutme.txt file that contains solution to the version control task.

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
You did not name the aboutMe folder properly. There should be no spacing in namings, you could either use camel-casing or make it small letters all through.

**Comment by Kafabidemi** [comment]
> You did not name the aboutMe folder properly. There should be no spacing in namings, you could either use camel-casing or make it small letters all through.

Done now, kindly review

**Comment by Kafabidemi** [comment]
Corrected.
Kindly review.
Thanks

**Review by Ireti203 — CHANGES_REQUESTED** [review]
You should use camel-casing. aboutMe or AboutMe

**Pull request closed without merging**
