### PR TITLE
[DFMD-1] My First Pull Request

### PR DESCRIPTION
**Pull request by MoyinoluwaA**
Created about me folder

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Weldone @MoyinoluwaA You should create an aboutMe folder in MoyinoluwaAdenuga folder.  That is where you will place the .txt file.

**Comment by MoyinoluwaA** [comment]
Thanks. That's what I did. I created an aboutMe folder with the aboutMe.txt file.

**Comment by Ireti203** [comment]
No, you havent created the aboutMe folder. The same way you created MoyinoluwaAdenuga folder, create a folder named aboutMe, then place aboutMe.txt file in the aboutMe folder. Do you understand?

**Comment by MoyinoluwaA** [comment]
I am so sorry. Mistakenly, the file wasn't in the folder. I have made the requested change @Ireti203

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
