### PR TITLE
[159] Create & Style the Customer Signup Page using CSS

### PR DESCRIPTION
**Pull request by Blessing-Hubb**
Task: Create and style sign up page
I created and styled sign up page
mobilesign1
mobilesign2
mobilesign3
signuptab1
signuptab2
signupdesktop
signupdesk2

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Your html files are not properly formatted. Kindly format properly

**Comment by Ireti203** [comment]
Weldone @Blessing-Hubb

**Comment by Blessing-Hubb** [comment]
Html file properly formatted

**Comment by Blessing-Hubb** [comment]
I followed the instruction by clicking on format and word wrap on the notepad editor

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
