### PR TITLE
[154] Style the Product Details Page using CSS

### PR DESCRIPTION
**Pull request by HalimahOladimeji**
Laptop view
Screenshot 2020-12-03 133052
Screenshot 2020-12-03 133202
Tablet view
Screenshot 2020-12-03 155442
Mobile view
Screenshot 2020-12-03 160753
Screenshot 2020-12-03 160848

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @HalimahOladimeji The mobile screen looks quite different from the mock up. The font size in the footer is not consistent.

Also, the links in the header are not positioned as what we have we have in the mockup.

**Comment by HalimahOladimeji** [comment]
I have made and updated the changes.

**Comment by Ireti203** [comment]
The font size of the tablet view is too big. Also, you did not attach screenshots for mobile.

**Comment by HalimahOladimeji** [comment]
I have made the changes and added the mobile view.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
