### PR TITLE
[DFFE-2] Develop a Product Page using HTML

### PR DESCRIPTION
**Pull request by Boluwatt**
Screenshot (1)
Screenshot (2)
Screenshot (3)

### CODE REVIEW

**Comment by Ireti203** [comment]
You are to add the screenshots of the product page you worked on, not screenshot of git..

**Comment by Boluwatt** [comment]
> You are to add the screenshots of the product page you worked on, not screenshot of git..

Done ma.

**Comment by Boluwatt** [comment]
Thanks for the correction. I was confused when the task said "add a
screenshot of the implementation to your PR". I have made the necessary
changes. Please look into it and merge my work so I can move on to the next
stage. Thank you.

**Review by adaugochi — APPROVED** [review]

**Comment by Boluwatt** [comment]
Awesome, thanks!

**Pull request merged**
