### PR TITLE
[DEFE-6] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by kaozarat16**
contactpage
contactpage 2
tab contactpage
tab contact page 2
phone contact page
phone contactpage 2

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done @kaozarat16 

I still feel it can be better. The labels on the form shouldn't be centralized. Same goes for the input field. Kindly take a look at the mockup again

**Comment by kaozarat16** [comment]
contactpage 1
contactpage 2
tabcontactpage
tabcontactpage 2
phonecontactpage 1
phone contactpage 2

**Comment by adaugochi** [comment]
Well done. You are making progress. Kindly work on this section of the page marked yellow
image

**Comment by kaozarat16** [comment]
adjusted

**Pull request merged**
