### PR TITLE
[DFFS-9] Printing Product Price with javaScript

### PR DESCRIPTION
**Pull request by Mayowa2020**
Proper naming of my PR Title

### CODE REVIEW

**Comment by Ireti203** [comment]
Add a screenshot of your console to this PR

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Remove spaces in image names. Also, what is the focus of this PR exactly...I thought it should contain the html file and js for printing product price. Or has the PR been created before?

**Comment by Mayowa2020** [comment]
Screenshot (257)
Attached herewith is the screenshot of my console to this PR

**Comment by Mayowa2020** [comment]
Yes, the PR had been created before, this js file was linked to the
Product.html file in the HTML folder. But I have now created a
separate html file for this based on your comment above.

**Comment by Mayowa2020** [comment]
Screenshot (258)
Screenshot (259)
Screenshot (260)
Screenshot (261)
Please find attached the screenshots of my console.
Screenshot (262)

**Comment by Ireti203** [comment]
You still have spaces in some of the image names

**Comment by Mayowa2020** [comment]
Screenshot (263)

Attached herewith is a screenshot of my console, showing the removal of the white spaces in the image names.

**Comment by Mayowa2020** [comment]
Awaiting your re-review.

**Pull request merged**
