### PR TITLE
[DFFE-9] Printing Product Price with JavaScript

### PR DESCRIPTION
**Pull request by Blessing-Hubb**
#Task: Print product price
I added product list print out
productlist

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Your PR contains a .png file. I expect to see an html file and a js file showing your code. Kindly ensure you are pushing the right thing.

**Comment by Blessing-Hubb** [comment]
Okay, this was not specified in the acceptance criteria so I did  everything on a console
 I will do that and push again

**Comment by Blessing-Hubb** [comment]
I have added html and js file

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Kindly remove the productlist.png image in the javascript folder

**Comment by Blessing-Hubb** [comment]
I removed that already before pushing

**Review by adaugochi — CHANGES_REQUESTED** [review]
remove space 
image

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
