### PR TITLE
[DFFA-6] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by Seyi01**
Screenshot (29)
Screenshot (28)

### CODE REVIEW

**Comment by Ireti203** [comment]
Your footer is not visible in the screenshot. Kindly upload a screenshot that shows the footer.

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Remove spaces from your image names.

**Comment by Seyi01** [comment]
Screenshot (30)
Screenshot (32)

these are the required screenshots.

 I don't understand the second observation as the image names are just one-word?

Please, kindly review my first task also ma as it is still pending. Thanks

**Comment by Seyi01** [comment]
> Remove spaces from your image names.

Understood and done ma. Kindly review (both PRs).

**Review by Ireti203 — APPROVED** [review]

**Comment by Ireti203** [comment]
Kindly resolve the conflicts on this PR..

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Kindly resolve the conflicts

**Comment by Seyi01** [comment]
Please I don't understand the conflicts. Please can you explain how to resolve it ma'am

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
