### PR TITLE
[148] Add Page Navigation to your Pages

### PR DESCRIPTION
**Pull request by Hamdalat001**
contact_form
product

### CODE REVIEW

**Review by adaugochi — COMMENTED** [review]
I think you don't really understand what you are meant to do for this task.

- first, you don't have to create a new contactform or product page file again. You already did that in your previous task. What you did now is simply repetition.

**Comment by adaugochi** [comment]
And I have said it before, Don't create more than one PR at a time

**Comment by HamdyB** [comment]
@adaugochi, sorry about the multiple PRs. I didn't create new pages. I just linked them.

**Comment by Hamdalat001** [comment]
@adaugochi, I apologize for the multiple PRs. I didn't create new pages. I just linked them and put in screenshots.

**Review by adaugochi — CHANGES_REQUESTED** [review]
image
image

As you can see, you already have index.html and contact.html page. You don't have to create them again because that's what you are doing. All you need to do is to create a link that will link these pages together. Such that if I am on the index page and I click contact us, it will take me to  contact page and vice versa

**Comment by Hamdalat001** [comment]
@adaugochi, thanks for the clarification. I've fixed it

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
