### PR TITLE
[152] Style the Product Details Page using CSS - Frontend

### PR DESCRIPTION
**Pull request by Immaculeta1**
styled the product page using css

### CODE REVIEW

**Comment by Immaculeta1** [comment]
Capture1
Capture2

**Comment by Immaculeta1** [comment]
Capture1
Capture2

**Comment by Ireti203** [comment]
There are conflicts on this branch, you should resolve it.

**Review by Ireti203 — COMMENTED** [review]
This PR ought to contain only the styling for the product page. I can see you are pushing other files that has previously been merged e.g the aboutMe.txt file ought not to be a part of this PR. Kindly make changes.

**Comment by adaugochi** [comment]
Add a screenshot of what this page looks like on mobile devices

**Review by adaugochi — CHANGES_REQUESTED** [review]
I can't find your styling for product page. I can only see HTML page only

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
