### PR TITLE
[DFFS-7] Style the Product Details Page using CSS

### PR DESCRIPTION
**Pull request by RafiatAmin**
Screen Shot 2021-02-28 at 8 35 39 PM
Screen Shot 2021-02-28 at 8 35 52 PM
Screen Shot 2021-02-28 at 9 00 40 PM
Screen Shot 2021-02-28 at 9 00 50 PM
Screen Shot 2021-02-28 at 9 01 22 PM
Screen Shot 2021-02-28 at 9 01 46 PM
Screen Shot 2021-02-28 at 9 02 00 PM

### CODE REVIEW

**Comment by adaugochi** [comment]
Well done @RafiatAmin 

The first screenshot you posted, the navigation links should be centrally placed. It shouldn't be placed at the top

**Comment by RafiatAmin** [comment]
Screen Shot 2021-03-03 at 11 14 18 AM

Thank you, I've fixed it, committed and pushed the changes

**Comment by Ireti203** [comment]
Your changes is not visible on the PR. Ensure you are pushing your changes correctly.

**Comment by RafiatAmin** [comment]
Okay, I have committed it now. 
Screen Shot 2021-03-03 at 11 14 18 AM

**Review by adaugochi — CHANGES_REQUESTED** [review]
All images should be in the images folder that is in your `html` folder.

You can decide to create an `icons` folder in your `images` folder

**Comment by RafiatAmin** [comment]
Okay. I’ve done that

**Review by adaugochi — CHANGES_REQUESTED** [review]
DIdn't you make any changes to your existing productPage.html file?

**Comment by RafiatAmin** [comment]
No, just the styles page

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
