### PR TITLE
[DFFS-6] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by Constancia2**
Desktopview1
desktopview2
desktopview 3
mobileview 1
mobileview 2

### CODE REVIEW

**Comment by adaugochi** [comment]
Well done so far @Constancia2 

But, I still think you can do better. From what I can see on the screenshots. The form field doesn't look like that on the mockup. Kindly do a rework

**Comment by Constancia2** [comment]
I tried using padding left to adjust the form but it's not moving ,then the
message logo I used text-align: centre; still didn't move . Pls how can I
adjust it

**Review by adaugochi — CHANGES_REQUESTED** [review]
What about the `contact.html` page? I can only see the css file

**Comment by adaugochi** [comment]
Unattended to

**Pull request closed without merging**
