### PR TITLE
[138] Product Page using  HTML

### PR DESCRIPTION
**Pull request by desorllah**

### CODE REVIEW

**Comment by Ireti203** [comment]
You still have unused images in the folder. Kindly remove them.

**Comment by desorllah** [comment]
> You still have unused images in the folder. Kindly remove them.

**Comment by desorllah** [comment]
> You still have unused images in the folder. Kindly remove them.

Which images please...are you referring to the screenshots or the images I used for the html page coz I've deleted the one I didn't use in the HTML.... I'm also trying to push it...it's saying everything is up to date...so please clarify the picture I am to delete ??

**Comment by Ireti203** [comment]
The images are product-page 1, 2 and 3 in your HTML folder.

**Pull request closed without merging**
