### PR TITLE
[152] Style the product Details Page using CSS- Frontend 

### PR DESCRIPTION
**Pull request by kaozarat16**
productpage
tab product page 1
tab product page 2
phone product page 1
phone product page 2

### CODE REVIEW

**Comment by Ireti203** [comment]
The mobile view can be improved on. The entire description is not showing on the view.

**Comment by Ireti203** [comment]
Add the screenshot showing the changes

**Comment by kaozarat16** [comment]
Okay

**Comment by kaozarat16** [comment]
productpage phone 1
productpage phone 2

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done @kaozarat16 

But, didn't you make changes to the product page HTML file?

**Pull request closed without merging**
