### PR TITLE
[DFFA-5] Create and Style the Customer Sign-up Page

### PR DESCRIPTION
**Pull request by Seyi01**
Screenshot (23)
Screenshot (24)

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @Seyi01 You can improve on this. The input fields doesn't look like what we have on the mock up. The links on the header isn't at the right position as well.

**Comment by Seyi01** [comment]
Screenshot (27)
Screenshot (26)

I have made necessary changes ma'am. Thank you

**Review by Ireti203 — CHANGES_REQUESTED** [review]
You haven't removed the space in this image name i.e "fruit hill"

**Comment by Seyi01** [comment]
> You haven't removed the space in this image name i.e "fruit hill"

Just did. Thank you.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
