### PR TITLE
[142] Develop a Contact Form Page using HTML

### PR DESCRIPTION
**Pull request by RafiatAmin**
Screen Shot 2020-12-03 at 10 36 33 AM

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
You have two contact form files. Remove the html-forms folder in the HTML folder since you are not using it.

**Comment by RafiatAmin** [comment]
Screen Shot 2020-12-11 at 10 16 24 AM

This is my folder, I moved it since already

**Comment by Ireti203** [comment]
From your PR, you have an html-forms folder in your HTML folder. Remove it since it's not being used there.

**Comment by Ireti203** [comment]
If you have removed it, you probably didnt push your changes, because it is not  being effected on your PR

**Review by adaugochi — CHANGES_REQUESTED** [review]
You mistakenly push these file. Kindly locate it and remove it 
image
image

**Pull request closed without merging**
