### PR TITLE
[DFFE-9] Printing Product Price with JavaScript 

### PR DESCRIPTION
**Pull request by Immaculeta1**
created array called product list

### CODE REVIEW

**Comment by Ireti203** [comment]
Kindly add the screenshot of your console

**Comment by Ireti203** [comment]
Also, your PR title isn't correct. Use the updated task title on the app

**Comment by Immaculeta1** [comment]
Capture

**Comment by Immaculeta1** [comment]
> Kindly add the screenshot of your console

done

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
