### PR TITLE
[150] Add Page Navigation to your Pages

### PR DESCRIPTION
**Pull request by olakanmigoodnessb**

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
This PR doesnt show any of the html files with the navigation. Kindly update this PR by pushing the html files where you added the navigation links.

**Comment by olakanmigoodnessb** [comment]
I'm so sorry, I just found out I pushed from a different branch. I re-pushed from the appropriate branch and this is the link.
https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/286

Thank you.

**Review by adaugochi — CHANGES_REQUESTED** [review]
Hello

**Comment by adaugochi** [comment]
@olakanmigoodnessb If that's the case kindly close this branch. Don't leave it open

**Comment by olakanmigoodnessb** [comment]
Alright. Thank you.

**Pull request closed without merging**
