### PR TITLE
[156] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by Blessing-Hubb**
Task: style your contact page
I styled my contact page
contactmob1
contactmob2
contacttab1
contacttab 3
contact pic

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @Blessing-Hubb. The icons on the footer seem quite far apart. You should reduce the spacing a bit.

**Comment by Blessing-Hubb** [comment]
done
modified

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Kindly format the product.html file properly.

**Comment by Blessing-Hubb** [comment]
Product.html file formatted

**Review by Ireti203 — CHANGES_REQUESTED** [review]
The product.html file is still not properly formatted. You can right click in your editor and use the format document option.

**Comment by Blessing-Hubb** [comment]
I just did followed the instruction now(i cIicked on format and word wrap)
I  am using notepad.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
