### PR TITLE
[DFMD-2] Develop a Product Page Using HTML

### PR DESCRIPTION
**Pull request by Peace-Peter**
Created a product page for an online elecricals store

screenshot

image

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
You have earlier created the aboutme.txt file...you dont have to create it again. Kindly remove it from this PR

**Comment by Ireti203** [comment]
Kindly resolve the conflicts on this PR

**Comment by Peace-Peter** [comment]
Good afternoon.

Please how can I resolve the conflict? Do I start the PR process all over
again? Or there's another way?

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Remove the spacing in your file names e.g Product Page.html is better written as ProductPage.html

**Review by Ireti203 — CHANGES_REQUESTED** [review]
You are required to have only two images for this task. Kindly remove the unused ones..

**Comment by Peace-Peter** [comment]
Done.


Please kindly review.

**Review by adaugochi — APPROVED** [review]

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
