### PR TITLE
[156] Style the Contact Us Page using CSS - Frontend

### PR DESCRIPTION
**Pull request by kaozarat16**
contactpage
tab contact page 1
tab contact page 2
phone contact page
phone contactpage 2

### CODE REVIEW

**Comment by Ireti203** [comment]
Kindly avoid opening two PRs at the same time so you don't get things mixed up. Ensure a previously opened PR gets merged before opening another.

**Comment by Ireti203** [comment]
You can open this PR when your previous PR gets merged

**Comment by kaozarat16** [comment]
productpage phone 1
productpage phone 2

**Comment by kaozarat16** [comment]
I'm so sorry, that was a mistake

**Pull request closed without merging**
