### PR TITLE
Product Page Using HTML

### PR DESCRIPTION
**Pull request by cindyemeh**

### CODE REVIEW

**Comment by Ireti203** [comment]
The PR title is not the same as what was recommended on the task criteria.

**Comment by Ireti203** [comment]
**Proffered Solution**
Open your pull request page
Scroll down the page and close the pull request
Switch to a new branch, update your changes on the new branch and create a new PR with the recommended title on the task criteria e.g [DFFS-1] My First Pull Request.

**Comment by cindyemeh** [comment]
Hello,

The title as seen in the mobile app is [DFFE-2] Develop a Product Page
Using HTML.

The title used in the PR is Product Page Using HTML.

Should I still change this?

Thank you.

**Comment by adaugochi** [comment]
Wrong PR title. Kindly create a new PR

**Comment by cindyemeh** [comment]
The changes have been made and a new PR has been created.

Kindly assist and review.

Thank you!
--
Regards
Cindy

**Pull request closed without merging**
