### PR TITLE
[DFFS-9] Printing Product Price with JavaScript

### PR DESCRIPTION
**Pull request by RafiatAmin**
In case things look a bit different, my PC is faulty and I will be committing my tasks via anyone I can lay hands on. Thanks for understanding

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
The html and js file ought to be in your folder in the submissions folder. If you are using another PC, I believe you must have cloned the project again..so you still have the submissions folder. Kindly place your files in the appropriate directory.

**Review by adaugochi — CHANGES_REQUESTED** [review]
Kindly delete this file 
image it is part of your PR

**Comment by RafiatAmin** [comment]
I have deleted and committed the changes. I just hope it appears in the appropriate folder

**Comment by Ireti203** [comment]
You still dont have your work in that right directory.

**Pull request closed without merging**
