### PR TITLE
[DFFA-7] Style the Product Details Page using CSS

### PR DESCRIPTION
**Pull request by O-mobola**
Screenshot_20210506_224504

Screenshot_20210506_224348

### CODE REVIEW

**Comment by O-mobola** [comment]
> Weldone @O-mobola. Kindly attach the screenshot for mobile. Also, the font size for the tablet screen-size is too big.
> 
The mobile is the second image

> The nav-links on the top bar is also quite different from the mock-up. Kindly adhere to the mock-up.

Ok.

**Comment by adaugochi** [comment]
Well done

**Review by adaugochi — COMMENTED** [review]
Well done @OmolayoO

I love your work. But, what you didn't share with us is how it look on laptop or desktop view. I can only see tablet and phone view

**Comment by adaugochi** [comment]
> Weldone @O-mobola. Kindly attach the screenshot for mobile. Also, the font size for the tablet screen-size is too big.
> 
> The nav-links on the top bar is also quite different from the mock-up. Kindly adhere to the mock-up.

I think is it ok

**Comment by O-mobola** [comment]
> Well done @OmolayoO
> 
> I love your work. But, what you didn't share with us is how it look on laptop or desktop view. I can only see tablet and phone view

Yeah, I'm sorry about that. I got an issue with my system currently, I am only  using my phone.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
