### PR TITLE
[139] Product Page using HTML

### PR DESCRIPTION
**Pull request by Aarinolaa**
image

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Remove the spaces in your image names

**Comment by Aarinolaa** [comment]
I don't' understand please, what exactly do i do? is it the Golden Penny Pasta?

**Comment by Ireti203** [comment]
> I don't' understand please, what exactly do i do? is it the Golden Penny Pasta?

Yes, and other image files. There should be no spacing in the naming i.e you should have GoldenPennyPasta or goldenpennypasta, no spacing

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Kindly remove the .docx file in the html folder. Also, ensure you are pushing the right content of the ProductPage.html fle

**Comment by Aarinolaa** [comment]
I'm not sure why the images are not loading again after i renamed and removed the spaces. i have deleted the spaces in the terminal too. please as I'm now confused

**Comment by Aarinolaa** [comment]
I have made the correction, kindly review. Thanks.

image

**Comment by Ireti203** [comment]
You have to effect the changes you made in the filenames in your html code.

**Comment by Aarinolaa** [comment]
Hi Ireti, I have made the changes, kindly review. thanks

**Review by Ireti203 — CHANGES_REQUESTED** [review]
I can't view the ProductPage.html file. Are you sure you are pushing the file correctly?

**Comment by Aarinolaa** [comment]
Thank you for your response, I was pushing the whole folder instead of the file itself. kindly review, hopefully I have it right this time

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
