### PR TITLE
[149] Add Page Navigation to your Pages

### PR DESCRIPTION
**Pull request by kaozarat16**
Capture
Capturee

### CODE REVIEW

**Comment by Ireti203** [comment]
There are conflicts on this branch, you should resolve it.

**Comment by Ireti203** [comment]
Also, why did you open another PR with the same title as the one you earlier opened.

**Comment by kaozarat16** [comment]
I made some changes, then opened and closed but it didn't reflect on the apl

**Comment by kaozarat16** [comment]
I'll just close it, since it's the same thing with the other one.

Thank you

**Pull request closed without merging**
