### PR TITLE
[DFFS-6] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by RafiatAmin**
Screen Shot 2021-02-28 at 11 41 54 AM
Screen Shot 2021-02-28 at 11 42 14 AM
Screen Shot 2021-02-28 at 11 42 48 AM
Screen Shot 2021-02-28 at 11 42 58 AM
Screen Shot 2021-02-28 at 11 43 16 AM
Screen Shot 2021-02-28 at 11 43 23 AM

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @RafiatAmin The logo on the header is not showing. Kindly confirm that the image link is correct

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Remove the spaces in your file and folder names e.g icon images

**Comment by RafiatAmin** [comment]
Yes, it’s correct. I’ll re-upload it once my designer sends the transparent png format.

**Comment by RafiatAmin** [comment]
Done. I've committed and pushed.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
