### PR TITLE
[134] About Me

### PR DESCRIPTION
**Pull request by Constancia2**

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
weldone @Constancia2 Kindly rename the .txt file to something more descriptive e.g aboutme.txt.
Rename the folder titled about-me as aboutMe.
Remove the hyphen (-) in Onyediri-Constancia. Camel-casing could either be onyediriConstancia or OnyediriConstancia.

**Comment by Constancia2** [comment]
Thanks for the correction, pls after pushing to github will I still make
another pull request ?

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Your .txt file should be aboutme.txt and not aboutme.txt.txt. Kindly correct this

**Comment by Constancia2** [comment]
I typed aboutme.txt , I really don't know why it's showing that . I don't
know how else to correct that .

**Comment by Ireti203** [comment]
You must have attempted creating a text document...a .txt extension would be added by default. There is an extra .txt because you also added another in your naming. You can remove it.

**Comment by Constancia2** [comment]
I have removed and pushed . Thank you

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
