### PR TITLE
[152] Style the Product Details Page using CSS

### PR DESCRIPTION
**Pull request by saidatatanda**
I added CSS styles to my product details page and edited my products page html file to suit my css styles
IMG-6197
IMG-6198

IMG-6179

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
well done @saidatatanda 

You have merge conflict on your PR. You have to resolve it

**Comment by saidatatanda** [comment]
How do I go about resolving this please?

**Comment by adaugochi** [comment]
Kindly check the first pinned message on the #git-versioncontrol channel on slack. There is a process to guide you. If you still don't understand, kindly reach out @saidatatanda

**Comment by adaugochi** [comment]
Kindly update your PR title to the new task title that is on the app. Going forward, I will have to close this PR so you can then create a new one

**Pull request closed without merging**
