### PR TITLE
[136] About Me

### PR DESCRIPTION
**Pull request by Mistura-Yusuf**
[136] About Me
I added a my expectation.txt file that contains solution to the git and version control task.

### CODE REVIEW

**Comment by Ireti203** [comment]
Your PR does contain any file, Kindly ensure you are pushing your changes correctly.

**Review by adaugochi — CHANGES_REQUESTED** [review]
Kindly locate this folder on your project. It is part of your PR. you have to remove it
image

**Review by Mistura-Yusuf — COMMENTED** [review]
Good Day, I have removed the file as requested.
thank you

**Comment by Mistura-Yusuf** [comment]
Please review my PR.
Thank you

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
