### PR TITLE
[153] Style the Product Details Page using CSS-Fullstack

### PR DESCRIPTION
**Pull request by Constancia2**
desktopview 1
Desktopview 2
mobileview 1
mobile view 2
mobileview 3

### CODE REVIEW

**Comment by adaugochi** [comment]
You have merge conflict kindly resolve it

**Comment by Constancia2** [comment]
I don't know how to resolve it ma .

**Comment by adaugochi** [comment]
I tagged you on a post, did you see it?

**Comment by Constancia2** [comment]
No ma ,I didn't see anything

**Pull request closed without merging**
