### PR TITLE
[137] Product Page using HTML

### PR DESCRIPTION
**Pull request by Posannie**
Screenshot (96)
Screenshot (97)
Screenshot (98)

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Remove the spacing in the image file names

**Comment by Posannie** [comment]
I just effected the changes on the folder. Do I need to commit these changes?




On Tuesday, December 1, 2020, 4:07 PM, Ireti203 <notifications@github.com> wrote:




@Ireti203 requested changes on this pull request.

Remove the spacing in the image file names

**Comment by Posannie** [comment]
I made the changes on the code as well. 




On Tuesday, December 1, 2020, 4:07 PM, Ireti203 <notifications@github.com> wrote:




@Ireti203 requested changes on this pull request.

Remove the spacing in the image file names

**Comment by Ireti203** [comment]
I can't see your changes, you should commit and push it to the branch.

**Comment by Posannie** [comment]
Oh ok...will do so now. 




On Wednesday, December 2, 2020, 6:56 AM, Ireti203 <notifications@github.com> wrote:




I can't see your changes, you should commit and push it to the branch.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
