### PR TITLE
[40] About Me

### PR DESCRIPTION
**Pull request by saidatatanda**

### CODE REVIEW

**Comment by saidatatanda** [comment]
I have effected the changes with the correct PR title.

**Comment by Dufuna-Fem** [comment]
Your title should include the identifier in the square brackets [ ]. Please update your Title to the correct one.

**Comment by saidatatanda** [comment]
> Your title should include the identifier in the square brackets [ ]. Please update your Title to the correct one.

Do I have to close the PR first?

**Comment by Ireti203** [comment]
Weldone @saidatatanda Kindly close the PR and open it again with the correct title instead.

**Pull request closed without merging**
