### PR TITLE
[DFFA-6] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by O-mobola**
Screenshot_20210516_111743

Screenshot_20210516_111515

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @O-mobola The social media icons are missing on the footer. Also, the input field on the footer ought to be for email address.

**Comment by adaugochi** [comment]
A quick reminder that you have comment on your PR

**Comment by O-mobola** [comment]
> Weldone @O-mobola The social media icons are missing on the footer. Also, the input field on the footer ought to be for email address.

Ok, I will work on it, thanks.

**Comment by O-mobola** [comment]
> A quick reminder that you have comment on your PR

I will work on it, thanks

**Pull request merged**
