### PR TITLE
[138] Product Page using HTML

### PR DESCRIPTION
**Pull request by Badabee**
Screen Shot 2021-01-31 at 3 48 06 AM

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
@Badabee You are pushing changes from other scholars folder. Kindly ensure you are only pushing only changes from your folder.

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Also remove the .gitignore.txt file you created.

**Comment by Ireti203** [comment]
Kindly confirm that the PR title is same as what you have on the task criteria

**Comment by adaugochi** [comment]
Wrong PR title

**Pull request closed without merging**
