### PR TITLE
[199] Printing Product Price with Javascript 

### PR DESCRIPTION
**Pull request by OluwaboriShobayo**
image

### CODE REVIEW

**Review by Ireti203 — CHANGES_REQUESTED** [review]
This PR does not show your file(s). Kindly ensure you are pushing your changes correctly

**Comment by Ireti203** [comment]
There are conflicts on your PR. Kindly resolve it

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done @OluwaboriShobayo 

But, this is what you are meant to do. You are to create an array of object. Then loop through that array and console.log what you are asked to output

**Comment by OluwaboriShobayo** [comment]
> Well done @OluwaboriShobayo
> 
> But, this is what you are meant to do. You are to create an array of object. Then loop through that array and console.log what you are asked to output

Thanks @adaugochi, But, I don't understand what you meant by looping through; there were no conditions specified in the task.

**Comment by OluwaboriShobayo** [comment]
> Well done @OluwaboriShobayo
> 
> But, this is what you are meant to do. You are to create an array of object. Then loop through that array and console.log what you are asked to output

@adaugochi Thanks for the correction, I have modified it.

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
