### PR TITLE
[DFFE-5] Create & Style the Customer Signup Page

### PR DESCRIPTION
**Pull request by Badabee**
Screenshot 2021-03-27 at 23 44 35
Screenshot 2021-03-27 at 23 45 01

### CODE REVIEW

**Review by adaugochi — COMMENTED** [review]
- your `signup.css` file should be inside the `CSS` folder.
- For the `signup.html` file, should be inside the `html-forms` folder
- For this task, you are to work only on the `signup form`, but I am seeing the `contact` page and `product` page. You will have to remove them
- Also, attach a screenshot of the mobile view of what you designed

**Comment by Badabee** [comment]
All file locations have been updated as requested, kindly review.
Also, find below screenshots of the Ipad and mobile screen for your perusal. 

Screenshot 2021-03-31 at 08 15 35
Screenshot 2021-03-31 at 08 16 04
Screenshot 2021-03-31 at 08 17 34
Screenshot 2021-03-31 at 08 17 50

**Review by adaugochi — COMMENTED** [review]
All images should be inside the images folder that is in your HTML folder

**Comment by Badabee** [comment]
Image location has been updated, kindly review.

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
