### PR TITLE
[152]Style the Product Details Page Using CSS -Frontend

### PR DESCRIPTION
**Pull request by Lillian-1**
changes done.

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Kindly add a screenshot of what you did

**Comment by Lillian-1** [comment]
Screenshot 2020-12-15 171828
screenshot1
Screenshot 2020-12-15 172034
Screenshot 2020-12-15 171904
Screenshot 2020-12-15 171938
Screenshot 2020-12-15 172000
tablet1
tablet2

**Comment by Lillian-1** [comment]
Good evening. I’ve added the screenshot as requested 


Sent from Yahoo Mail for iPhone


On Tuesday, December 15, 2020, 4:58 PM, Maryfaith Mgbede <notifications@github.com> wrote:




@adaugochi requested changes on this pull request.

Kindly add a screenshot of what you did

**Review by Ireti203 — CHANGES_REQUESTED** [review]
Why do you have the html file in a css folder? The index.html file should be in a html folder not in a css folder

**Review by Ireti203 — APPROVED** [review]

**Pull request merged**
