### PR TITLE
[DFFS-7] Style the Product Details Page using CSS

### PR DESCRIPTION
**Pull request by Constancia2**
Desktopview 1
desktopview 2
mobile view 1
mobileview 2
mobileview 3

### CODE REVIEW

**Review by adaugochi — CHANGES_REQUESTED** [review]
Well done @Constancia2 
We are indeed making progress
But, there is one more thing you have to do.
Some currently you have some images inside `HTML` folder and some inside `HTML-FORMS` folder.
Kindly move all the images in `HTML-FORMS` folder into the `Images` folder that is in your `HTML` folder

**Comment by Constancia2** [comment]
Done ma

**Comment by Ireti203** [comment]
You still have some images in the HTML-FORMS folder...you should move the images to the HTML folder

**Comment by Constancia2** [comment]
It is empty at my end ,I don't know why it is still showing . I don't know
how else to resolve it because I have removed it

**Comment by Constancia2** [comment]
Or am I supposed to push each of the folder one after the other again ? I
don't know how else to solve it because I re push the last folder I was
working on after removing the images as you suggested.

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
