### PR TITLE
[135] About Me

### PR DESCRIPTION
**Pull request by saidatatanda**
I have closed and reopened another PR.

### CODE REVIEW

**Comment by Ireti203** [comment]
Can you please confirm that the number you have in the square bracket is same as what you have in the task criteria?

**Comment by saidatatanda** [comment]
I have changed the title

**Comment by saidatatanda** [comment]
Oh! I thought I was to use the identifier referenced in the previous email.
I have changed it now.

**Comment by Ireti203** [comment]
Weldone @saidatatanda I can see that you edited the title to make the change. Kindly close the PR and create a new one using the correct title.

**Pull request closed without merging**
