### PR TITLE
[DFFE-5] Create & Style the Customer Signup Page

### PR DESCRIPTION
**Pull request by saidatatanda**
I created a signup page and added css styles to it. I also edited my product and contact pages css. 
IMG_6954
IMG_6953
IMG_6952

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @saidatatanda The screenshots you shared doesn't show the footer area. Kindly update the screenshot.

**Comment by saidatatanda** [comment]
image
image
image

**Comment by Ireti203** [comment]
On mobile and tablet screens, the footer items are too close to the extreme left. It will look better if you give  a litttle padding.

**Comment by saidatatanda** [comment]
image
image

**Comment by Ireti203** [comment]
Weldone @saidatatanda

**Pull request merged**
