### PR TITLE
[DFFS-6] Style the Contact Us Page using CSS

### PR DESCRIPTION
**Pull request by Kifaayah**
productmobile
productpageTablet
productweb

### CODE REVIEW

**Comment by Ireti203** [comment]
There shouldnt be space beneath your footer.

**Comment by Ireti203** [comment]
Kindly resolve the conflicts on this PR

**Comment by adaugochi** [comment]
If you are finding this difficult to resolve, kindly reach out to me on Monday

**Comment by adaugochi** [comment]
Long overdue PR

**Pull request closed without merging**
