### PR TITLE
[DFFS-5] Create & Style the Customer Signup Page

### PR DESCRIPTION
**Pull request by RafiatAmin**
Screen Shot 2021-02-22 at 7 50 21 PM
Screen Shot 2021-02-22 at 7 50 38 PM

### CODE REVIEW

**Comment by Ireti203** [comment]
Weldone @RafiatAmin Kindly add the screenshot for tablet and mobile screens

**Comment by Ireti203** [comment]
Also, it will look better if you make the text in the sign-up button white. I mean the sign-up button in the form.

**Review by adaugochi — CHANGES_REQUESTED** [review]
I can't see the HTML file for the signup form page. I can only see the css file

**Comment by RafiatAmin** [comment]
> I can't see the HTML file for the signup form page. I can only see the css file

I will work on it. Thanks

**Pull request closed without merging**
