### PR TITLE
[DFFE-110] Product Array Algorithm

### PR DESCRIPTION
**Pull request by OmolayoO**
image

@Ireti203 @adaugochi

### CODE REVIEW

**Review by adaugochi — COMMENTED** [review]
You are still deleting other peoples work

**Comment by OmolayoO** [comment]
No, I am not.
Please clarify.

Sent from Yahoo Mail on Android 
 
  On Wed, 12 May 2021 at 2:31 pm, Adaa ***@***.***> wrote:   


@adaugochi commented on this pull request.

You are still deleting other peoples work

**Review by adaugochi — COMMENTED** [review]
Visit this link https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/892/files to see your PR. Note that what is colored red, are the things you removed, and green is what you added

**Comment by OmolayoO** [comment]
I didn't delete other people's work.
I didn't push those either.
I don't know why multiple files keeps getting pushed to Git.
I also don't know why all this are showing.
I tried pulling from the remote repository, after which I noticed some other files showing.
How can this be corrected so we don't keep going back and forth. This is the 7th branch I have tried creating with this particular task and I have tried everything possible and it is still pushing multiple files.

Sent from Yahoo Mail on Android 
 
  On Wed, 12 May 2021 at 3:58 pm, Adaa ***@***.***> wrote:   


@adaugochi commented on this pull request.

Visit this link https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/892/files to see your PR

**Comment by adaugochi** [comment]
> I didn't delete other people's work. I didn't push those either. I don't know why multiple files keeps getting pushed to Git. I also don't know why all this are showing. I tried pulling from the remote repository, after which I noticed some other files showing. How can this be corrected so we don't keep going back and forth. This is the 7th branch I have tried creating with this particular task and I have tried everything possible and it is still pushing multiple files. Sent from Yahoo Mail on Android On Wed, 12 May 2021 at 3:58 pm, Adaa ***@***.***> wrote: @adaugochi commented on this pull request. Visit this link https://github.com/Dufuna-CodeCamp/Dufuna-Fem/pull/892/files to see your PR — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Send me a DM privately on the channel

**Pull request closed without merging**
